part of 'helpers.dart';

const String screenSplash = "/";
const String screenWelcome = "/welcome";
const String screenContentCaching = "/content_caching";
const String screenIntro = "/intro";
const String screenRegister = "/register";
const String screenRegisterTv = "/register-tv";
const String screenSettings = "/settings";
const String screenFavourite = "/favourite";
const String screenCatchUp = "/catchup";
const String screenUsersList = "/users-list";
const String screenMovies = "/movies";
const String screenSeries = "/series";
const String screenLiveCategories = "/categories-live";
const String screenMovieCategories = "/categories-movie";
const String screenSeriesCategories = "/categories-series";
const String screenDeviceActivation = "/device-activation";
const String screenUserInfo = "/user_info";
const String screenDownloadedMovies = "/downloaded-movies";
