// File generated by Firebase CLI.
// This file contains the Firebase configuration for your Flutter app.
// Replace the placeholder values with your actual Firebase project configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for your app
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Web
    if (kIsWeb) {
      return web;
    }
    // Mobile/desktop platforms
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these placeholder values with your actual Firebase project configuration
  // You can find these values in your Firebase project settings

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDYcRGTs8X174Ja5IyAnkyeiwRMlvg174Y",
    authDomain: "iptvsmarterspro-23f22.firebaseapp.com",
    projectId: "iptvsmarterspro-23f22",
    storageBucket: "iptvsmarterspro-23f22.firebasestorage.app",
    messagingSenderId: "443921573314",
    appId: "1:443921573314:web:0b2afb2c1ef1723a41625b",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDYcRGTs8X174Ja5IyAnkyeiwRMlvg174Y",
    authDomain: "iptvsmarterspro-23f22.firebaseapp.com",
    projectId: "iptvsmarterspro-23f22",
    storageBucket: "iptvsmarterspro-23f22.firebasestorage.app",
    messagingSenderId: "443921573314",
    appId: "1:443921573314:web:0b2afb2c1ef1723a41625b",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );
}
